baseurl = "http://www.jonathanc.xyz/book-notes/"
languageCode = "en-us"
title = "jonathan's book notes"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
# themesDir = "../.."

[params]
    site_author = "Jonathan Coleman"
    # site_description = "My Book Notes"
    # location = "Earth"
    # Link custom assets relative to /static
    avatar = "images/Jonathan_Coleman_Flat_Avatar_cropped_150px.png"
    header_background = "images/books.jpg"
    header_title = "jonathan's book notes"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    # twitter   = "spf13"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    # github    = "digitalcraftsman"
    gplus     = ""
